version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/blu/"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/intake"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/intake/build"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/intake/parse"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/intake/read"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/nomnom"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/nomnom/examples/csv"
      schedule:
          interval: "daily"
