on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 16, 18]
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: ./blur
            - run: npm run build
              working-directory: ./blur
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: ./intake
            - run: npm run build
              working-directory: ./intake
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: ./nomnom
            - run: npm run build
              working-directory: ./nomnom
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: ./intake/packages/parse
            - run: npm run build
              working-directory: ./intake/packages/parse
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: ./intake/packages/read
            - run: npm run build
              working-directory: ./intake/packages/read
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
              working-directory: ./nomnom/examples/csv
            - run: npm run build
              working-directory: ./nomnom/examples/csv
