on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x 14.x, 16.x, 18.x]
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: pnpm/action-setup@v2.2.3
              with:
                  version: 7.13.4
                  run_install: |
                      - recursive: true
                        args: [ --shamefully-hoist=true, --child-concurrency=9999, --network-concurrency=9999, --prefer-frozen-lockfile=false, --strict-peer-dependencies=false, --unsafe-perm=true, --lockfile-only ]


            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: './blur/pnpm-lock.yaml'
            - run: pnpm install
              working-directory: ./blur


            - run: pnpm run build
              working-directory: ./blur


            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: './intake/pnpm-lock.yaml'
            - run: pnpm install
              working-directory: ./intake


            - run: pnpm run build
              working-directory: ./intake


            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: './nomnom/pnpm-lock.yaml'
            - run: pnpm install
              working-directory: ./nomnom


            - run: pnpm run build
              working-directory: ./nomnom


            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: './intake/packages/parse/pnpm-lock.yaml'
            - run: pnpm install
              working-directory: ./intake/packages/parse


            - run: pnpm run build
              working-directory: ./intake/packages/parse


            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: './intake/packages/read/pnpm-lock.yaml'
            - run: pnpm install
              working-directory: ./intake/packages/read


            - run: pnpm run build
              working-directory: ./intake/packages/read


            - uses: actions/setup-node@v3.5.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: './nomnom/examples/csv/pnpm-lock.yaml'
            - run: pnpm install
              working-directory: ./nomnom/examples/csv


            - run: pnpm run build
              working-directory: ./nomnom/examples/csv
