name: NPM

concurrency:
    group: npm-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3.5.3
            - uses: actions/setup-node@v3.6.0
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"
            - run: npm install -g npm

            - name: Publish ./blur
              continue-on-error: true
              working-directory: ./blur
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./intake
              continue-on-error: true
              working-directory: ./intake
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./intake/packages/nomnom
              continue-on-error: true
              working-directory: ./intake/packages/nomnom
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./intake/packages/parse
              continue-on-error: true
              working-directory: ./intake/packages/parse
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./intake/packages/read
              continue-on-error: true
              working-directory: ./intake/packages/read
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./nomnom/examples/csv
              continue-on-error: true
              working-directory: ./nomnom/examples/csv
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
